YOUTUBE_API_KEY = "AIzaSyCrRxETzD4hgRUCYNTagp568iSvbEgEEak"
OPENAI_API_KEY= "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"
